import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/global/large-navbar';
import Footer from '@/components/global/large-footer';

const inter = Montserrat({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'AYNcore E-commerce',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${inter.className} bg-darkcolor`}>
        <Navbar />
        <main className='main flex-1'>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
